name: Generate and Commit Hello Messages

on:
  workflow_dispatch:  # Permite ejecutar el flujo manualmente desde GitHub
  schedule:
    - cron: "*/5 * * * *"  # Opcional: Ejecutar cada 5 minutos (ajusta según sea necesario)

jobs:
  generate-and-commit:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tienes dependencias en requirements.txt

    - name: Run generate_hello.py script
      run: |
        python generate_hello.py

    - name: Commit and push generated JSON
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Add generated hello messages JSON"
        file_pattern: "hello_messages.json"
